{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-creds
  labels:
    {{- include "csqe.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-user: {{ .Values.minio.rootUser | quote }}
  root-password: {{ .Values.minio.rootPassword | quote }}
{{- end }}
---
{{- if .Values.fuseki.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-fuseki-creds
  labels:
    {{- include "csqe.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.fuseki.adminPassword | quote }}
{{- end }}
